disabled_rules:
  - closure_parameter_position
  - discarded_notification_center_observer
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - nesting
  - type_body_length
  - type_name
  - trailing_comma
  - weak_delegate
  - redundant_optional_initialization
  - force_try
  - todo
opt_in_rules:
  - empty_count
  - force_unwrapping
  - private_outlet
line_length: 125
type_body_length:
  warning: 300
  error: 400
included:
 - Tinylog
excluded:
  - Pods
  - TinylogTests
  - TinylogUITests
  - vendor
