language: swift
osx_image: xcode11.2
notifications:
  email: true
branches:
  only:
    - develop
    - master

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - gem install cocoapods
  - gem install xcpretty -N
  - make bootstrap
  - make secrets

jobs:
  include:
    - stage: lint
      script:
        - ./Pods/SwiftLint/swiftlint --reporter junit

    - stage: build
      script:
        - make build

    - stage: test
      script:
        - make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
