language: swift
osx_image: xcode10

branches:
  only:
    - develop
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.6.0
  - gem install cocoapods
  - gem install xcpretty -N
  - make bootstrap
  - make secrets
script:
  - set -o pipefail
  - make build
  - make test
