# The Deliverfile allows you to store various iTunes Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier "com.spirosgerokostas.Tinylog" # The bundle identifier of your app
username "spiros.gerokostas@gmail.com" # your Apple ID user